const PDFDocument = require("pdfkit");

const { generateStudyPlan } = require("./studyPlanService");
const { generateCompanyRoadmap } = require("./companyRoadmapService");

// =======================================
// Generate AI Analysis
// =======================================

function generateAIAnalysis(stats = {}) {

    const analysis = [];

    // Total Solved
    if ((stats.totalSolved || 0) >= 500) {

        analysis.push(
            "Excellent consistency. You are solving at an advanced level."
        );

    } else if ((stats.totalSolved || 0) >= 300) {

        analysis.push(
            "Very good progress. Keep maintaining your coding consistency."
        );

    } else if ((stats.totalSolved || 0) >= 150) {

        analysis.push(
            "Good progress. You are building a strong DSA foundation."
        );

    } else {

        analysis.push(
            "You are in the learning phase. Solve problems daily."
        );

    }

    // Hard Problems
    if ((stats.hardSolved || 0) >= 100) {

        analysis.push(
            "Outstanding Hard problem-solving skills."
        );

    } else if ((stats.hardSolved || 0) >= 40) {

        analysis.push(
            "Good Hard problem-solving ability."
        );

    } else {

        analysis.push(
            "Increase Hard problem practice for interview preparation."
        );

    }

    // Medium Problems
    if ((stats.mediumSolved || 0) >= 150) {

        analysis.push(
            "Excellent Medium problem coverage."
        );

    } else {

        analysis.push(
            "Focus more on Medium-level problems."
        );

    }

    // Ranking
    if ((stats.ranking || Infinity) < 100000) {

        analysis.push(
            "Excellent global ranking."
        );

    } else if ((stats.ranking || Infinity) < 300000) {

        analysis.push(
            "Good global ranking."
        );

    } else {

        analysis.push(
            "Continue solving consistently to improve your ranking."
        );

    }

    return analysis;
}

// =======================================
// Generate Report PDF
// =======================================

const generateReportPDF = (user) => {

    return new Promise((resolve, reject) => {

        try {

            const doc = new PDFDocument({
                size: "A4",
                margin: 50
            });

            // PDF Metadata
            doc.info.Title = "LeetMetricAI Report";
            doc.info.Author = "LeetMetricAI";
            doc.info.Subject = "LeetCode Performance Report";
            doc.info.Creator = "LeetMetricAI";

            const buffers = [];

            doc.on("data", chunk => buffers.push(chunk));

            doc.on("end", () => {
                resolve(Buffer.concat(buffers));
            });

            // Footer Function
            const addFooter = () => {

                doc.fontSize(10)
                    .fillColor("gray")
                    .text(
                        "Generated by LeetMetricAI",
                        50,
                        doc.page.height - 50,
                        {
                            align: "center"
                        }
                    );

            };

            
            const stats = user.leetcodeStats || {};

            // ===================================
            // Title
            // ===================================

            doc
                .fontSize(26)
                .fillColor("#2563EB")
                .text(
                    "LeetMetricAI Performance Report",
                    {
                        align: "center"
                    }
                );

            doc.moveDown(1.2);

            // ===================================
            // User Information
            // ===================================

            doc
                .fontSize(18)
                .fillColor("#111827")
                .text("User Information");

            doc.moveDown(0.5);

            doc.fontSize(13);

            doc.text(`Name : ${user.name}`);

            doc.text(
                `LeetCode Username : ${
                    user.leetcodeUsername || "Not Synced"
                }`
            );

            doc.text(
                `Generated On : ${new Date().toLocaleString()}`
            );

            doc.moveDown();

            // ===================================
            // LeetCode Statistics
            // ===================================

            doc
                .fontSize(18)
                .fillColor("#2563EB")
                .text("LeetCode Statistics");

            doc.moveDown(0.5);

            doc.fontSize(13);

            doc.text(`Total Solved : ${stats.totalSolved || 0}`);

            doc.text(`Easy : ${stats.easySolved || 0}`);

            doc.text(`Medium : ${stats.mediumSolved || 0}`);

            doc.text(`Hard : ${stats.hardSolved || 0}`);

            doc.text(`Ranking : ${stats.ranking || "N/A"}`);

            doc.text(`Reputation : ${stats.reputation || 0}`);

            doc.moveDown();

            // ===================================
            // AI Analysis
            // ===================================

            const aiAnalysis = generateAIAnalysis(stats);

            doc
                .fontSize(18)
                .fillColor("#2563EB")
                .text("AI Performance Analysis");

            doc.moveDown(0.5);

            doc.fontSize(13);

            aiAnalysis.forEach(item => {
                doc.text(`• ${item}`);
            });

            doc.moveDown();

            // ===================================
            // Study Plan
            // ===================================

            const studyPlan = generateStudyPlan(stats);

            doc
                .fontSize(18)
                .fillColor("#16A34A")
                .text("Personalized Study Plan");

            doc.moveDown(0.5);

            doc.fontSize(13);

            studyPlan.forEach(item => {
                doc.text(`• ${item}`);
            });

            doc.moveDown();

                        // ===================================
            // Company Roadmap
            // ===================================

            const roadmap = generateCompanyRoadmap(stats);

            doc
                .fontSize(18)
                .fillColor("#DC2626")
                .text("Company Preparation Roadmap");

            doc.moveDown(0.5);

            doc.fontSize(13);

            roadmap.forEach(item => {

                doc
                    .font("Helvetica-Bold")
                    .text(item.company);

                doc
                    .font("Helvetica")
                    .text(`Focus: ${item.focus}`);

                doc.moveDown(0.5);

            });

            doc.moveDown();

            // ===================================
            // Summary
            // ===================================

            doc
                .fontSize(18)
                .fillColor("#7C3AED")
                .text("Final Summary");

            doc.moveDown(0.5);

            let summary = "";

            if ((stats.totalSolved || 0) >= 500) {

                summary =
                    "You are interview-ready for most top product-based companies. Continue revising advanced topics and participate in contests regularly.";

            } else if ((stats.totalSolved || 0) >= 300) {

                summary =
                    "You have built a strong DSA foundation. Focus on Hard problems, contest practice, and mock interviews.";

            } else if ((stats.totalSolved || 0) >= 150) {

                summary =
                    "Good progress so far. Increase Medium and Hard problem solving consistency and strengthen important interview patterns.";

            } else {

                summary =
                    "Focus on solving problems daily, mastering fundamental data structures, and building coding consistency.";

            }

            doc
                .fontSize(13)
                .fillColor("black")
                .text(summary, {
                    align: "justify"
                });

            doc.moveDown(2);

            // ===================================
            // Footer
            // ===================================
            doc.fontSize(10)
            .fillColor("gray")
            .text(
                "Generated by LeetMetricAI",
                50,
                doc.page.height - 50,
                {
                    align: "center"
                }
            );
            addFooter();

            // Finish PDF
            doc.end();

        } catch (error) {

            reject(error);

        }

    });

};

module.exports = {
    generateReportPDF
};